[package]
name = "tokio_learn"
version = "0.1.0"
authors = ["liukaizeng <1051299241@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3.4", features = ["full"] }
rand = "*"
